SER502-Spring-2017-Team10: src/compiler/byte_code.c File Reference
byte_code.c File Reference
Purpose: byte code operation.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include "utils/link_list.h"
#include "utils/symbol_table.h"
#include "utils/parsing_tree.h"
#include "utils/error.h"
#include "byte_code.h"
Functions
static int handle_if_stmt_helper (parsing_tree_st *then_node)
static void byte_code_new (link_list_st *, char *, char *, char *)
static void handle_stmt_list (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
handle stmt_list from parsing tree.
static void handle_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
handle stmt from parsing tree.
static char * handle_boolean_value (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate boolean_value byte code from parsing tree.
static char * handle_boolean_expr (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate boolean_expr byte code from parsing tree.
static void handle_if_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate if_stmt byte code from parsing tree.
static void handle_for_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate for_stmt byte code from parsing tree.
static char * handle_expr (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
handle expr form parsing tree and symbol table.
static char * handle_term (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
handle term form parsing tree and symbol table.
static void handle_decl_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate decl_stmt byte code from parsing tree.
static void handle_assign_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate assign_stmt byte code from parsing tree.
static void handle_print_stmt (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate print_stmt byte code from parsing tree.
static char * handle_res1 (parsing_tree_st *parsing_tree_node, link_list_st *byte_code, char *terms_data)
generate res1 byte code form link list and parsing tree.
static char * handle_factor (parsing_tree_st *parsing_tree_node, link_list_st *byte_code)
generate factor byte code form link list and parsing tree.
static char * handle_res2 (parsing_tree_st *parsing_tree_node, link_list_st *byte_code, char *factors_data)
generate res2 byte code form link list and parsing tree.
int get_digits_num (int int_num)
link_list_st * semantic_analysis (parsing_tree_st *parsing_tree_node, symbol_table_st *symbol_table)
generate byte code from parsing tree and symbol table.
Variables
static int temp_id = 0
static int loop_id = 0
static int if_id = 0
static int else_id = 0
Detailed Description
Purpose: byte code operation.
Version
1.0
Date
04.18.2017
Author
Rundong Zhu
Definition in file byte_code.c.
Function Documentation
byte_code_new()
static void byte_code_new (link_list_st * byte_code, char * op_code, char * first_oprand, char * second_oprand) static
Definition at line 716 of file byte_code.c.
References link_list_append(), and link_node_new().
Referenced by handle_assign_stmt(), handle_boolean_expr(), handle_decl_stmt(), handle_for_stmt(), handle_if_stmt(), handle_print_stmt(), handle_res1(), and handle_res2().
get_digits_num()
int get_digits_num (int int_num)
Definition at line 66 of file byte_code.c.
Referenced by handle_for_stmt(), handle_if_stmt(), handle_res1(), and handle_res2().
handle_assign_stmt()
static void handle_assign_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate assign_stmt byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 184 of file byte_code.c.
References byte_code_new(), error_msg(), handle_expr(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_stmt().
handle_boolean_expr()
static char * handle_boolean_expr (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate boolean_expr byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Returns
boolean operator.
Definition at line 495 of file byte_code.c.
References byte_code_new(), error_msg(), handle_boolean_value(), handle_expr(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_if_stmt().
handle_boolean_value()
static char * handle_boolean_value (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate boolean_value byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Returns
boolean value, "1" for true, "0" for false.
Definition at line 481 of file byte_code.c.
References parsing_tree_get_child(), and parsing_tree_get_data().
Referenced by handle_boolean_expr().
handle_decl_stmt()
static void handle_decl_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate decl_stmt byte code from parsing tree.
Parameters
node,a valid tree node
byte_code,a valid link list.
Definition at line 167 of file byte_code.c.
References byte_code_new(), error_msg(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_stmt().
handle_expr()
static char * handle_expr (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
handle expr form parsing tree and symbol table.
Parameters
byte_code,a valid link list.
node,a valid tree node.
Returns
NULL on failed, otherwise a char array.
Definition at line 533 of file byte_code.c.
References error_errno(), handle_res1(), handle_term(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_assign_stmt(), handle_boolean_expr(), handle_factor(), handle_for_stmt(), and handle_print_stmt().
handle_factor()
static char * handle_factor (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate factor byte code form link list and parsing tree.
Parameters
byte_code,a valid link list.
node,a valid tree node.
Returns
NULL on failed, otherwise a char array.
Definition at line 636 of file byte_code.c.
References handle_expr(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_res2(), and handle_term().
handle_for_stmt()
static void handle_for_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate for_stmt byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 339 of file byte_code.c.
References byte_code_new(), error_msg(), get_digits_num(), handle_expr(), handle_stmt_list(), loop_id, parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_stmt().
handle_if_stmt()
static void handle_if_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate if_stmt byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 210 of file byte_code.c.
References byte_code_new(), else_id, error_msg(), get_digits_num(), handle_boolean_expr(), handle_if_stmt_helper(), handle_stmt_list(), if_id, parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_stmt().
handle_if_stmt_helper()
static int handle_if_stmt_helper (parsing_tree_st * then_node) static
Definition at line 732 of file byte_code.c.
References LINK_LIST_CONTINUE, link_list_free(), LINK_LIST_STOP, link_list_traverse(), link_node_get_data(), main(), parsing_tree_free(), parsing_tree_get_data(), parsing_tree_get_sibling(), parsing_tree_new(), parsing_tree_prefix_traverse(), parsing_tree_set_child(), parsing_tree_set_sibling(), print_byte_code(), semantic_analysis(), and TREE_TRAVERSE_CONTINUE.
Referenced by handle_if_stmt().
handle_print_stmt()
static void handle_print_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
generate print_stmt byte code from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 456 of file byte_code.c.
References byte_code_new(), error_msg(), handle_expr(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_stmt().
handle_res1()
static char * handle_res1 (parsing_tree_st * parsing_tree_node, link_list_st * byte_code, char * terms_data) static
generate res1 byte code form link list and parsing tree.
Parameters
byte_code,a valid link list.
node,a valid tree node.
Returns
NULL on failed, otherwise a char array.
Definition at line 581 of file byte_code.c.
References byte_code_new(), error_msg(), get_digits_num(), handle_term(), parsing_tree_get_child(), parsing_tree_get_data(), parsing_tree_get_sibling(), and temp_id.
Referenced by handle_expr().
handle_res2()
static char * handle_res2 (parsing_tree_st * parsing_tree_node, link_list_st * byte_code, char * factors_data) static
generate res2 byte code form link list and parsing tree.
Parameters
byte_code,a valid link list.
node,a valid tree node.
Returns
NULL on failed, otherwise a valid link list.
Definition at line 662 of file byte_code.c.
References byte_code_new(), error_errno(), error_msg(), get_digits_num(), handle_factor(), parsing_tree_get_child(), parsing_tree_get_data(), parsing_tree_get_sibling(), and temp_id.
Referenced by handle_term().
handle_stmt()
static void handle_stmt (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
handle stmt from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 143 of file byte_code.c.
References error_msg(), handle_assign_stmt(), handle_decl_stmt(), handle_for_stmt(), handle_if_stmt(), handle_print_stmt(), parsing_tree_get_child(), and parsing_tree_get_data().
Referenced by handle_stmt_list().
handle_stmt_list()
static void handle_stmt_list (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
handle stmt_list from parsing tree.
Parameters
node,a valid tree node.
byte_code,a valid link list.
Definition at line 111 of file byte_code.c.
References error_msg(), handle_stmt(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_for_stmt(), handle_if_stmt(), and semantic_analysis().
handle_term()
static char * handle_term (parsing_tree_st * parsing_tree_node, link_list_st * byte_code) static
handle term form parsing tree and symbol table.
Parameters
byte_code,a valid link list.
node,a valid tree node.
Returns
NULL on failed, otherwise a char array.
Definition at line 557 of file byte_code.c.
References error_errno(), handle_factor(), handle_res2(), parsing_tree_get_child(), parsing_tree_get_data(), and parsing_tree_get_sibling().
Referenced by handle_expr(), and handle_res1().
semantic_analysis()
link_list_st* semantic_analysis (parsing_tree_st * parsing_tree_node, symbol_table_st * symbol_table)
generate byte code from parsing tree and symbol table.
generate byte code form parsing tree and symbol table.
Parameters
node,a valid tree node.
table,a valid symbol table object
Returns
NULL on failed, otherwise a valid link list.
Definition at line 81 of file byte_code.c.
References handle_stmt_list(), link_list_init(), parsing_tree_get_child(), and parsing_tree_get_data().
Referenced by handle_if_stmt_helper(), and main().
Variable Documentation
else_id
int else_id = 0 static
Definition at line 59 of file byte_code.c.
Referenced by handle_if_stmt().
if_id
int if_id = 0 static
Definition at line 57 of file byte_code.c.
Referenced by handle_if_stmt().
loop_id
int loop_id = 0 static
Definition at line 55 of file byte_code.c.
Referenced by handle_for_stmt().
temp_id
int temp_id = 0 static
Definition at line 53 of file byte_code.c.
Referenced by handle_res1(), and handle_res2().