SER502-Spring-2017-Team10: src/runtime/storage.c File Reference
storage.c File Reference
Purpose: implementation of the machine storage.
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "storage.h"
Classes
struct memory
struct machine_memory
Macros
#define STATIC_MEMORY_SIZE (32)
memory size of the virtual machine
#define SCOPE_BOUNDRAY_SIZE (4)
array size of the scope boundray
#define RESIZE_FACTOR (2)
resize factor when memory size is too small
Functions
machine_memory_st * machine_memory_init ()
initialize the machine memory.
void machine_memory_fini (machine_memory_st *machine_store)
clean up the machine memory, release all resources.
memory_st * machine_memory_get_variable (machine_memory_st *machine_store, char *variable_name, int scope)
get a variable from the storage.
int machine_memory_set_variable (machine_memory_st *machine_store, char *variable_name, int value, int scope)
set a variable to the storage.
void machine_memory_open_scope (machine_memory_st *machine_store)
open a new scope on the machine memory
void machine_memory_close_scope (machine_memory_st *machine_store)
close current scope on the machine memory, will release all variables.
int memory_get_value (memory_st *variable)
get a value from memory object.
void memory_set_value (memory_st *variable, int value)
set a value to memory object.
Detailed Description
Purpose: implementation of the machine storage.
Version
1.0
Date
04.23.2017
Author
Xiangyu Guo
Definition in file storage.c.
Macro Definition Documentation
RESIZE_FACTOR
#define RESIZE_FACTOR (2)
resize factor when memory size is too small
Definition at line 17 of file storage.c.
Referenced by machine_memory_open_scope(), and machine_memory_set_variable().
SCOPE_BOUNDRAY_SIZE
#define SCOPE_BOUNDRAY_SIZE (4)
array size of the scope boundray
Definition at line 16 of file storage.c.
Referenced by machine_memory_init().
STATIC_MEMORY_SIZE
#define STATIC_MEMORY_SIZE (32)
memory size of the virtual machine
Definition at line 15 of file storage.c.
Referenced by machine_memory_init().
Function Documentation
machine_memory_close_scope()
void machine_memory_close_scope (machine_memory_st * machine_store)
close current scope on the machine memory, will release all variables.
Parameters
machine_store a valid machine_store.
Definition at line 187 of file storage.c.
References machine_memory::allocated_address, machine_memory::current_scope, memory::scope, machine_memory::scope_boundary, machine_memory::static_memory, memory::variable_name, and memory::variable_value.
Referenced by s_evaluate().
machine_memory_fini()
void machine_memory_fini (machine_memory_st * machine_store)
clean up the machine memory, release all resources.
Parameters
machine_store a valid machine storage object.
Definition at line 74 of file storage.c.
References machine_memory::allocated_address, machine_memory::scope_boundary, machine_memory::static_memory, and memory::variable_name.
Referenced by main().
machine_memory_get_variable()
memory_st* machine_memory_get_variable (machine_memory_st * machine_store, char * variable_name, int scope)
get a variable from the storage.
Parameters
machine_store a valid machine_store.
variable_name variable name.
scope 0 for current scope, -1 for all scope.
Returns
NULL on failed or doesn't exist; otherwise a pointer to variable_memory.
Definition at line 94 of file storage.c.
References machine_memory::allocated_address, machine_memory::current_scope, MEMORY_CURRENT_SCOPE, machine_memory::scope_boundary, machine_memory::static_memory, and memory::variable_name.
Referenced by eval_bin_op_helper(), eval_cmp(), eval_dec(), and eval_out().
machine_memory_init()
machine_memory_st* machine_memory_init ()
initialize the machine memory.
Returns
machine_store a valid machine_store.
Definition at line 40 of file storage.c.
References machine_memory::allocated_address, machine_memory::current_scope, machine_memory::memory_size, machine_memory::scope_boundary, SCOPE_BOUNDRAY_SIZE, machine_memory::scope_capacity, machine_memory::static_memory, and STATIC_MEMORY_SIZE.
Referenced by main().
machine_memory_open_scope()
void machine_memory_open_scope (machine_memory_st * machine_store)
open a new scope on the machine memory
Parameters
machine_store a valid machine_store.
Definition at line 161 of file storage.c.
References machine_memory::allocated_address, machine_memory::current_scope, RESIZE_FACTOR, machine_memory::scope_boundary, and machine_memory::scope_capacity.
Referenced by s_evaluate().
machine_memory_set_variable()
int machine_memory_set_variable (machine_memory_st * machine_store, char * variable_name, int value, int scope)
set a variable to the storage.
Parameters
machine_store a valid machine_store.
variable_name variable name.
variable_value variable value.
scope 0 for current scope, -1 for all scope.
Returns
0 on success, otherwise failed.
Definition at line 127 of file storage.c.
References machine_memory::allocated_address, machine_memory::current_scope, machine_memory::memory_size, RESIZE_FACTOR, memory::scope, machine_memory::static_memory, memory::variable_name, and memory::variable_value.
Referenced by eval_dec().
memory_get_value()
int memory_get_value (memory_st * variable)
get a value from memory object.
Parameters
variable_memory a valid memory object.
Returns
the value inside the memory object.
Definition at line 224 of file storage.c.
References memory::variable_value.
Referenced by eval_bin_op_helper(), eval_cmp(), and eval_out().
memory_set_value()
void memory_set_value (memory_st * variable, int value)
set a value to memory object.
Parameters
variable_memory a valid memory object.
variable_value a new value.
Definition at line 236 of file storage.c.
References memory::variable_value.
Referenced by eval_bin_op_helper().