SER502-Spring-2017-Team10: src/compiler/utils/parsing_tree.h File Reference
parsing_tree.h File Reference
Purpose: the node of parsing tree data structure.
Macros
#define TREE_TRAVERSE_CONTINUE (1)
keep traverse
#define TREE_TRAVERSE_STOP (0)
stop traverse
Typedefs
typedef struct parsing_tree parsing_tree_st
typedef void(* free_treenode_cb) (void *)
Call back function on free.
typedef int(* tree_traversal_cb) (parsing_tree_st *, void *)
call back function
Functions
parsing_tree_st * parsing_tree_new (void *data, free_treenode_cb free_func)
create a new parsing tree node.
void parsing_tree_free (parsing_tree_st *)
free a tree from this node recursively.
parsing_tree_st * parsing_tree_set_sibling (parsing_tree_st *, parsing_tree_st *)
set a sibling to current node.
parsing_tree_st * parsing_tree_set_child (parsing_tree_st *, parsing_tree_st *)
set a child to current node.
parsing_tree_st * parsing_tree_get_sibling (parsing_tree_st *)
get a sibling of current node.
parsing_tree_st * parsing_tree_get_child (parsing_tree_st *)
get a child of current node.
void * parsing_tree_get_data (parsing_tree_st *)
get the data stored inside the node
int parsing_tree_prefix_traverse (parsing_tree_st *, tree_traversal_cb, void *)
traverse the parsing tree in prefix order.
Detailed Description
Purpose: the node of parsing tree data structure.
Version
1.0
Date
04.15.2017
Author
Xiangyu Guo
Definition in file parsing_tree.h.
Macro Definition Documentation
TREE_TRAVERSE_CONTINUE
#define TREE_TRAVERSE_CONTINUE (1)
keep traverse
Definition at line 11 of file parsing_tree.h.
Referenced by generate_stmt_list(), handle_if_stmt_helper(), and parsing_tree_prefix_traverse().
TREE_TRAVERSE_STOP
#define TREE_TRAVERSE_STOP (0)
stop traverse
Definition at line 12 of file parsing_tree.h.
Referenced by parsing_tree_prefix_traverse().
Typedef Documentation
free_treenode_cb
typedef void(* free_treenode_cb) (void *)
Call back function on free.
Definition at line 17 of file parsing_tree.h.
parsing_tree_st
typedef struct parsing_tree parsing_tree_st
Definition at line 14 of file parsing_tree.h.
tree_traversal_cb
typedef int(* tree_traversal_cb) (parsing_tree_st *, void *)
call back function
Definition at line 19 of file parsing_tree.h.
Function Documentation
parsing_tree_free()
void parsing_tree_free (parsing_tree_st * tree_root)
free a tree from this node recursively.
Parameters
node,a valid tree node.
Definition at line 49 of file parsing_tree.c.
References parsing_tree::child, parsing_tree::data, parsing_tree::free_func, parsing_tree_free(), and parsing_tree::sibling.
Referenced by handle_if_stmt_helper(), main(), parsing_tree_free(), and parsing_tree_prefix_traverse().
parsing_tree_get_child()
parsing_tree_st* parsing_tree_get_child (parsing_tree_st * tree_root)
get a child of current node.
Parameters
node,a valid node.
Returns
child, NULL means no child on this node.
Definition at line 110 of file parsing_tree.c.
References parsing_tree::child.
Referenced by handle_assign_stmt(), handle_boolean_expr(), handle_boolean_value(), handle_decl_stmt(), handle_expr(), handle_factor(), handle_for_stmt(), handle_if_stmt(), handle_print_stmt(), handle_res1(), handle_res2(), handle_stmt(), handle_stmt_list(), handle_term(), parsing_tree_prefix_traverse(), and semantic_analysis().
parsing_tree_get_data()
void* parsing_tree_get_data (parsing_tree_st * tree_root)
get the data stored inside the node
Parameters
node,a valid node.
Returns
NULL on failed; otherwise the pointer to the data.
Definition at line 121 of file parsing_tree.c.
References parsing_tree::data.
Referenced by generate_stmt_list(), handle_assign_stmt(), handle_boolean_expr(), handle_boolean_value(), handle_decl_stmt(), handle_expr(), handle_factor(), handle_for_stmt(), handle_if_stmt(), handle_if_stmt_helper(), handle_print_stmt(), handle_res1(), handle_res2(), handle_stmt(), handle_stmt_list(), handle_term(), parsing_tree_prefix_traverse(), and semantic_analysis().
parsing_tree_get_sibling()
parsing_tree_st* parsing_tree_get_sibling (parsing_tree_st * tree_root)
get a sibling of current node.
Parameters
node,a valid node.
Returns
sibling, NULL means no sibling on this node.
Definition at line 99 of file parsing_tree.c.
References parsing_tree::sibling.
Referenced by handle_assign_stmt(), handle_boolean_expr(), handle_decl_stmt(), handle_expr(), handle_factor(), handle_for_stmt(), handle_if_stmt(), handle_if_stmt_helper(), handle_print_stmt(), handle_res1(), handle_res2(), handle_stmt_list(), handle_term(), and parsing_tree_prefix_traverse().
parsing_tree_new()
parsing_tree_st* parsing_tree_new (void * data, free_treenode_cb free_func)
create a new parsing tree node.
Parameters
data,the data of the tree node.
free_func,the function to free the data.
Returns
node a valid node.
Definition at line 31 of file parsing_tree.c.
References parsing_tree::child, parsing_tree::data, error_errno(), parsing_tree::free_func, and parsing_tree::sibling.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_boolean_value(), generate_decl_stmt(), generate_expre(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt(), generate_stmt_list(), generate_term(), handle_if_stmt_helper(), parsing_tree_prefix_traverse(), and syntax_analysis().
parsing_tree_prefix_traverse()
int parsing_tree_prefix_traverse (parsing_tree_st * tree_root, tree_traversal_cb cb_func, void * cb_data)
traverse the parsing tree in prefix order.
Parameters
node,a valid node.
cb_func,call back function on the node.
cb_data,data of the call back function.
Returns
1, on continue; 0, on stopped.
Definition at line 134 of file parsing_tree.c.
References parsing_tree::child, main(), parsing_tree_free(), parsing_tree_get_child(), parsing_tree_get_data(), parsing_tree_get_sibling(), parsing_tree_new(), parsing_tree_prefix_traverse(), parsing_tree_set_child(), parsing_tree_set_sibling(), parsing_tree::sibling, TREE_TRAVERSE_CONTINUE, and TREE_TRAVERSE_STOP.
Referenced by generate_stmt_list(), handle_if_stmt_helper(), and parsing_tree_prefix_traverse().
parsing_tree_set_child()
parsing_tree_st* parsing_tree_set_child (parsing_tree_st * tree_root, parsing_tree_st * child)
set a child to current node.
Parameters
root,a valid tree node.
child,a valid child node.
Returns
NULL on failed; otherwise the pointer to the child.
Definition at line 86 of file parsing_tree.c.
References parsing_tree::child.
Referenced by generate_boolean_expre(), generate_boolean_value(), generate_expre(), generate_factor(), generate_res1(), generate_res2(), generate_stmt(), generate_stmt_list(), generate_term(), handle_if_stmt_helper(), parsing_tree_prefix_traverse(), and syntax_analysis().
parsing_tree_set_sibling()
parsing_tree_st* parsing_tree_set_sibling (parsing_tree_st * tree_root, parsing_tree_st * sibling)
set a sibling to current node.
Parameters
root,a valid tree node.
sibling,a valid sibling node.
Returns
NULL on failed; otherwise the pointer to the sibling.
Definition at line 72 of file parsing_tree.c.
References parsing_tree::sibling.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_decl_stmt(), generate_expre(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt_list(), generate_term(), handle_if_stmt_helper(), and parsing_tree_prefix_traverse().