SER502-Spring-2017-Team10: src/runtime/runtime.c File Reference
runtime.c File Reference
Purpose: main entrance of the runtime.
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "storage.h"
#include "instruction.h"
Classes
struct operation
Typedefs
typedef void(* eval) (void *, void *)
function pointer of eval functions
typedef int(* cmp_cb) (int)
function pointer of compare functions
typedef struct operation operation_st
Functions
static void eval_bin_op_helper (void *, void *, char)
evaluate function of all binary operations
static void eval_dec (void *, void *)
evaluate function of "DEC" instruction
static void eval_mov (void *, void *)
evaluate function of "MOV" instruction
static void eval_out (void *, void *)
evaluate function of "OUT" instruction
static void eval_add (void *, void *)
evaluate function of "ADD" instruction
static void eval_sub (void *, void *)
evaluate function of "SUB" instruction
static void eval_mul (void *, void *)
evaluate function of "MUL" instruction
static void eval_div (void *, void *)
evaluate function of "DIV" instruction
static void eval_mod (void *, void *)
evaluate function of "MOD" instruction
static void eval_cmp (void *, void *)
evaluate function of "CMP" instruction
static void eval_je (void *, void *)
evaluate function of "JE" instruction
static void eval_jne (void *, void *)
evaluate function of "JNE" instruction
static void eval_jl (void *, void *)
evaluate function of "JL" instruction
static void eval_jle (void *, void *)
evaluate function of "JLE" instruction
static void eval_jg (void *, void *)
evaluate function of "JG" instruction
static void eval_jge (void *, void *)
evaluate function of "JGE" instruction
static void eval_jmp (void *, void *)
evaluate function of "JMP" instruction
static void eval_bool_op_helper (void *, void *, cmp_cb flag_cmp)
evaluate function of all boolean operations
static int cmp_je (int)
comparison function for "JE" instruction
static int cmp_jne (int)
comparison function for "JNE" instruction
static int cmp_jl (int)
comparison function for "JL" instruction
static int cmp_jle (int)
comparison function for "JLE" instruction
static int cmp_jg (int)
comparison function for "JG" instruction
static int cmp_jge (int)
comparison function for "JGE" instruction
static int cmp_jmp (int)
comparison function for "JMP" instruction
static void s_evaluate (instruction_set_st *)
evaluate the ASM program.
static void s_usage ()
print out the usage information of runtime.
int main (int argc, char *argv[])
main entrance of runtime.
Variables
static machine_memory_st * s_machine_store
environment storage during run time
static instruction_set_st * s_instructions
instuctions of the assembled asm
static operation_st g_operations []
all operations provided by runtime.
Detailed Description
Purpose: main entrance of the runtime.
Version
1.0
Date
04.16.2017
Author
Xiangyu Guo
Definition in file runtime.c.
Typedef Documentation
cmp_cb
typedef int(* cmp_cb) (int)
function pointer of compare functions
Definition at line 21 of file runtime.c.
eval
typedef void(* eval) (void *, void *)
function pointer of eval functions
Definition at line 20 of file runtime.c.
operation_st
typedef struct operation operation_st
Function Documentation
cmp_je()
static int cmp_je (int flag) static
comparison function for "JE" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 701 of file runtime.c.
Referenced by eval_je().
cmp_jg()
static int cmp_jg (int flag) static
comparison function for "JG" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 737 of file runtime.c.
Referenced by eval_jg().
cmp_jge()
static int cmp_jge (int flag) static
comparison function for "JGE" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 746 of file runtime.c.
Referenced by eval_jge().
cmp_jl()
static int cmp_jl (int flag) static
comparison function for "JL" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 719 of file runtime.c.
Referenced by eval_jl().
cmp_jle()
static int cmp_jle (int flag) static
comparison function for "JLE" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 728 of file runtime.c.
Referenced by eval_jle().
cmp_jmp()
static int cmp_jmp (int flag) static
comparison function for "JMP" instruction
Parameters
flag the value of flag register.
Returns
1, unconditional jump, always be true.
Definition at line 755 of file runtime.c.
Referenced by eval_jmp().
cmp_jne()
static int cmp_jne (int flag) static
comparison function for "JNE" instruction
Parameters
flag the value of flag register.
Returns
compare result.
Definition at line 710 of file runtime.c.
Referenced by eval_jne().
eval_add()
static void eval_add (void * first_operand, void * second_operand) static
evaluate function of "ADD" instruction
Parameters
first first operand.
second second operand.
Definition at line 431 of file runtime.c.
References eval_bin_op_helper().
eval_bin_op_helper()
static void eval_bin_op_helper (void * first_operand, void * second_operand, char op_type) static
evaluate function of all binary operations
Parameters
first_operand,first operand.
second_operand,second operand.
op_type operation type.(+ - * / % =)
Definition at line 477 of file runtime.c.
References machine_memory_get_variable(), MEMORY_ALL_SCOPE, memory_get_value(), and memory_set_value().
Referenced by eval_add(), eval_div(), eval_mod(), eval_mov(), eval_mul(), and eval_sub().
eval_bool_op_helper()
static void eval_bool_op_helper (void * first_operand, void * second_operand, cmp_cb flag_cmp) static
evaluate function of all boolean operations
Parameters
first_operand,first operand.
second_operand,second operand.
flag_cmp call back function on different comparing behavior on flag
Definition at line 670 of file runtime.c.
References instruction_set_get_flag(), instruction_set_get_label(), and instruction_set_set_pc().
Referenced by eval_je(), eval_jg(), eval_jge(), eval_jl(), eval_jle(), eval_jmp(), and eval_jne().
eval_cmp()
static void eval_cmp (void * first_operand, void * second_operand) static
evaluate function of "CMP" instruction
Parameters
first first operand.
second second operand.
Definition at line 552 of file runtime.c.
References instruction_set_set_flag(), machine_memory_get_variable(), MEMORY_ALL_SCOPE, and memory_get_value().
eval_dec()
static void eval_dec (void * first_operand, void * second_operand) static
evaluate function of "DEC" instruction
Parameters
first first operand.
second second operand.
Definition at line 359 of file runtime.c.
References machine_memory_get_variable(), machine_memory_set_variable(), and MEMORY_CURRENT_SCOPE.
eval_div()
static void eval_div (void * first_operand, void * second_operand) static
evaluate function of "DIV" instruction
Parameters
first first operand.
second second operand.
Definition at line 458 of file runtime.c.
References eval_bin_op_helper().
eval_je()
static void eval_je (void * first_operand, void * second_operand) static
evaluate function of "JE" instruction
Parameters
first label.
second unused, will ignore.
flag flag value.
Definition at line 606 of file runtime.c.
References cmp_je(), and eval_bool_op_helper().
eval_jg()
static void eval_jg (void * first_operand, void * second_operand) static
evaluate function of "JG" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 642 of file runtime.c.
References cmp_jg(), and eval_bool_op_helper().
eval_jge()
static void eval_jge (void * first_operand, void * second_operand) static
evaluate function of "JGE" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 651 of file runtime.c.
References cmp_jge(), and eval_bool_op_helper().
eval_jl()
static void eval_jl (void * first_operand, void * second_operand) static
evaluate function of "JL" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 624 of file runtime.c.
References cmp_jl(), and eval_bool_op_helper().
eval_jle()
static void eval_jle (void * first_operand, void * second_operand) static
evaluate function of "JLE" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 633 of file runtime.c.
References cmp_jle(), and eval_bool_op_helper().
eval_jmp()
static void eval_jmp (void * first_operand, void * second_operand) static
evaluate function of "JMP" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 660 of file runtime.c.
References cmp_jmp(), and eval_bool_op_helper().
eval_jne()
static void eval_jne (void * first_operand, void * second_operand) static
evaluate function of "JNE" instruction
Parameters
first label.
second unused, will ignore.
Definition at line 615 of file runtime.c.
References cmp_jne(), and eval_bool_op_helper().
eval_mod()
static void eval_mod (void * first_operand, void * second_operand) static
evaluate function of "MOD" instruction
Parameters
first first operand.
second second operand.
Definition at line 467 of file runtime.c.
References eval_bin_op_helper().
eval_mov()
static void eval_mov (void * first_operand, void * second_operand) static
evaluate function of "MOV" instruction
Parameters
first first operand.
second second operand.
Definition at line 422 of file runtime.c.
References eval_bin_op_helper().
eval_mul()
static void eval_mul (void * first_operand, void * second_operand) static
evaluate function of "MUL" instruction
Parameters
first first operand.
second second operand.
Definition at line 449 of file runtime.c.
References eval_bin_op_helper().
eval_out()
static void eval_out (void * first_operand, void * second_operand) static
evaluate function of "OUT" instruction
Parameters
first first operand.
second second operand.
Definition at line 389 of file runtime.c.
References machine_memory_get_variable(), MEMORY_ALL_SCOPE, and memory_get_value().
eval_sub()
static void eval_sub (void * first_operand, void * second_operand) static
evaluate function of "SUB" instruction
Parameters
first first operand.
second second operand.
Definition at line 440 of file runtime.c.
References eval_bin_op_helper().
main()
int main (int argc, char * argv[])
main entrance of runtime.
Parameters
argc arguments count.
argv arguments vector.
Returns
0 on success; otherwise errno.
Definition at line 271 of file runtime.c.
References instruction_clean_up(), instruction_load_program(), machine_memory_fini(), machine_memory_init(), s_evaluate(), and s_usage().
s_evaluate()
static void s_evaluate (instruction_set_st * instructions) static
evaluate the ASM program.
Parameters
instruct_set [in] loaded instruction sequence.
Definition at line 310 of file runtime.c.
References operation::eval_func, instruction_get_op_code(), instruction_get_op_first(), instruction_get_op_second(), instruction_set_get_instruction(), machine_memory_close_scope(), machine_memory_open_scope(), and operation::op_code.
Referenced by main().
s_usage()
static void s_usage () static
print out the usage information of runtime.
Definition at line 300 of file runtime.c.
Referenced by main().
Variable Documentation
g_operations
operation_st g_operations[] static
Initial value:
= { {"DEC", eval_dec},
                                       {"MOV", eval_mov},
                                       {"OUT", eval_out},
                                       {"ADD", eval_add},
                                       {"SUB", eval_sub},
                                       {"MUL", eval_mul},
                                       {"DIV", eval_div},
                                       {"MOD", eval_mod},
                                       {"CMP", eval_cmp},
                                       {"JE" , eval_je },
                                       {"JNE", eval_jne},
                                       {"JL" , eval_jl },
                                       {"JLE", eval_jle},
                                       {"JG" , eval_jg },
                                       {"JGE", eval_jge},
                                       {"JMP", eval_jmp},
                                       {NULL , NULL} }
all operations provided by runtime.
Type 1: declare DEC var1 ; declare a variable
Type 2: assignment MOV var1, var2/value ; assign var2/value to var1
Type 3: arithmetic operation ADD var1, var2/value ; add var2/value to var1 SUB var1, var2/value ; sub var2/value from var1 MUL var1, var2/value ; mul var2/value to var1 DIV var1, var2/value ; div var2/value from var1 MOD var1, var2/value ; mod var1 with var2/value
Type 4: compare and jump operation CMP var1, var2/value ; CMP var1/value and var2/value, set $flag = var1/value - var2/value. JE label ; Jump to label if $flag Equal to zero. JNE label ; Jump to label if $flag Not Equal to zero. JL label ; Jump to label if $flag Less than zero. JLE label ; Jump to label if $flag Less than or Equal to zero. JG label ; Jump to label if $flag Great than zero. JGE label ; Jump to label if $flag Great than or Equal to zero. JMP label ; Jump to label, always.
Type 5: output result OUT var1/value ; Output var1/value.
Definition at line 236 of file runtime.c.
s_instructions
instruction_set_st* s_instructions static
instuctions of the assembled asm
Definition at line 29 of file runtime.c.
s_machine_store
machine_memory_st* s_machine_store static
environment storage during run time
Definition at line 28 of file runtime.c.