SER502-Spring-2017-Team10: src/compiler/parser.h File Reference
parser.h File Reference
Purpose: generate a parsing tree using token list and symbol table.
#include "utils/parsing_tree.h"
#include "utils/symbol_table.h"
#include "utils/link_list.h"
Functions
parsing_tree_st * syntax_analysis (link_list_st *token_list, symbol_table_st *symbol_table)
: get the token_list and symbol_table parse it into a parsing tree
Detailed Description
Purpose: generate a parsing tree using token list and symbol table.
Version
1.0
Date
04.18.2017
Author
Ximing
Definition in file parser.h.
Function Documentation
syntax_analysis()
parsing_tree_st* syntax_analysis (link_list_st * token_list, symbol_table_st * symbol_table)
: get the token_list and symbol_table parse it into a parsing tree
Parameters
Definition at line 557 of file parser.c.
References generate_stmt_list(), parsing_tree_new(), and parsing_tree_set_child().
Referenced by generate_stmt_list(), and main().