SER502-Spring-2017-Team10: src/compiler/utils/error.h File Reference
error.h File Reference
dealing with compiler error
Functions
void error_msg (int, char *)
print out the error message to stderr and exit the program
void error_errno (int)
print out the error message to stderr and exit the program
Detailed Description
dealing with compiler error
Version
1.0
Date
04.21.2017
Author
Xiangyu Guo
Definition in file error.h.
Function Documentation
error_errno()
void error_errno (int)
print out the error message to stderr and exit the program
Parameters
error_number error number
Definition at line 18 of file error.c.
Referenced by handle_expr(), handle_res2(), handle_term(), link_list_init(), link_node_new(), main(), parsing_tree_new(), and symbol_table_init().
error_msg()
void error_msg (int , char *)
print out the error message to stderr and exit the program
Parameters
lineno line number
msg error message
Definition at line 13 of file error.c.
Referenced by handle_assign_stmt(), handle_boolean_expr(), handle_decl_stmt(), handle_for_stmt(), handle_if_stmt(), handle_print_stmt(), handle_res1(), handle_res2(), handle_stmt(), and handle_stmt_list().