SER502-Spring-2017-Team10: src/compiler/byte_code.h File Reference
byte_code.h File Reference
Purpose: byte code operation.
#include "utils/link_list.h"
#include "utils/symbol_table.h"
#include "utils/parsing_tree.h"
#include "utils/error.h"
Functions
link_list_st * semantic_analysis (parsing_tree_st *, symbol_table_st *)
generate byte code form parsing tree and symbol table.
Detailed Description
Purpose: byte code operation.
Version
1.0
Date
04.18.2017
Author
Rundong Zhu
Definition in file byte_code.h.
Function Documentation
semantic_analysis()
link_list_st* semantic_analysis (parsing_tree_st * parsing_tree_node, symbol_table_st * symbol_table)
generate byte code form parsing tree and symbol table.
Parameters
node,a valid tree node.
table,a valid symbol table object
Returns
NULL on failed, otherwise a valid link list.
generate byte code form parsing tree and symbol table.
Parameters
node,a valid tree node.
table,a valid symbol table object
Returns
NULL on failed, otherwise a valid link list.
Definition at line 81 of file byte_code.c.
References handle_stmt_list(), link_list_init(), parsing_tree_get_child(), and parsing_tree_get_data().
Referenced by handle_if_stmt_helper(), and main().