SER502-Spring-2017-Team10: src/compiler/utils/link_node.h File Reference
link_node.h File Reference
Purpose: link_node data structure.
Typedefs
typedef struct link_node link_node_st
typedef void(* free_cb) (void *)
call back function on free
Functions
link_node_st * link_node_new (void *data, free_cb free_func)
creating a new node
void link_node_free (link_node_st *)
free a node
void * link_node_get_data (link_node_st *)
get the data from a node.
link_node_st * link_node_append (link_node_st *, link_node_st *)
append one node after the other.
link_node_st * link_node_get_next (link_node_st *)
get next node after current node.
void link_node_remove_all (link_node_st **)
remove all node start from current node.
Detailed Description
Purpose: link_node data structure.
Version
1.0
Date
04.15.2017
Author
Xiangyu Guo
Definition in file link_node.h.
Typedef Documentation
free_cb
typedef void(* free_cb) (void *)
call back function on free
Definition at line 14 of file link_node.h.
link_node_st
typedef struct link_node link_node_st
Definition at line 11 of file link_node.h.
Function Documentation
link_node_append()
link_node_st* link_node_append (link_node_st * node_prev, link_node_st * node_next)
append one node after the other.
Parameters
node_prev,the previous node.
node_next,the next node.
Returns
cursor, the latter one as cursor.
Definition at line 73 of file link_node.c.
References link_node::next.
Referenced by link_list_append(), link_list_pop(), and link_node_remove_all().
link_node_free()
void link_node_free (link_node_st * node)
free a node
Parameters
node,a valid node going to free.
Definition at line 44 of file link_node.c.
References link_node::data, link_node::free_func, and link_node::next.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_boolean_value(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt_list(), link_list_traverse(), and link_node_remove_all().
link_node_get_data()
void* link_node_get_data (link_node_st * node)
get the data from a node.
Parameters
node,a valid node.
Returns
NULL on failed; otherwise the pointer to the data.
Definition at line 60 of file link_node.c.
References link_node::data.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_boolean_value(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt(), generate_stmt_list(), handle_if_stmt_helper(), lexical_analysis(), link_list_traverse(), link_node_remove_all(), and print_byte_code().
link_node_get_next()
link_node_st* link_node_get_next (link_node_st * node)
get next node after current node.
Parameters
current_node,a valid node object.
Returns
next_node, next node of current node, otherwise NULL.
Definition at line 87 of file link_node.c.
References link_node::next.
Referenced by link_list_pop(), link_list_top(), and link_list_traverse().
link_node_new()
link_node_st* link_node_new (void * data, free_cb free_func)
creating a new node
Parameters
data,data of the node.
free_func,the function to free the data.
Returns
node, a valid node.
Definition at line 29 of file link_node.c.
References link_node::data, error_errno(), link_node::free_func, and link_node::next.
Referenced by byte_code_new(), emit_token(), generate_stmt_list(), link_list_init(), link_list_traverse(), and link_node_remove_all().
link_node_remove_all()
void link_node_remove_all (link_node_st ** head)
remove all node start from current node.
Parameters
head current node as head.
Definition at line 98 of file link_node.c.
References link_node_append(), link_node_free(), link_node_get_data(), link_node_new(), link_node_remove_all(), main(), and link_node::next.
Referenced by link_list_free(), and link_node_remove_all().