SER502-Spring-2017-Team10: src/runtime/instruction.h File Reference
instruction.h File Reference
Purpose: declaration of the machine instruction.
Typedefs
typedef struct instruction instruction_st
typedef struct instruction_set instruction_set_st
Functions
instruction_set_st * instruction_load_program (const char *)
load an ASM program into the runtime.
void instruction_clean_up (instruction_set_st *)
clean up the instruction set.
instruction_st * instruction_set_get_instruction (instruction_set_st *)
get next instruction from instruction set
void instruction_set_set_pc (instruction_set_st *, int)
set a new program counter
int instruction_set_get_flag (instruction_set_st *)
get the comparision result
void instruction_set_set_flag (instruction_set_st *, int)
set a new comparision result
unsigned int instruction_set_get_label (instruction_set_st *, char *)
look up a label address.
char * instruction_get_op_code (instruction_st *)
get operation code from an instruction.
char * instruction_get_op_first (instruction_st *)
get operation code from an instruction.
char * instruction_get_op_second (instruction_st *)
get operation code from an instruction.
Detailed Description
Purpose: declaration of the machine instruction.
Version
1.0
Date
04.23.2017
Author
Xiangyu Guo
Definition in file instruction.h.
Typedef Documentation
instruction_set_st
typedef struct instruction_set instruction_set_st
Definition at line 14 of file instruction.h.
instruction_st
typedef struct instruction instruction_st
Definition at line 11 of file instruction.h.
Function Documentation
instruction_clean_up()
void instruction_clean_up (instruction_set_st * instructions)
clean up the instruction set.
Parameters
instructions,a valid instruction set object.
Definition at line 117 of file instruction.c.
References instruction_set::count, instruction_set::instructs, label_info::label_name, label_table::label_table, label_table::label_table_size, instruction_set::labels, instruction::op_code, instruction::op_first, and instruction::op_second.
Referenced by main().
instruction_get_op_code()
char* instruction_get_op_code (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
op_code, operation code
Definition at line 232 of file instruction.c.
References instruction::op_code.
Referenced by s_evaluate().
instruction_get_op_first()
char* instruction_get_op_first (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
operand, first operand
Definition at line 243 of file instruction.c.
References instruction::op_first.
Referenced by s_evaluate().
instruction_get_op_second()
char* instruction_get_op_second (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
operand, second operand
Definition at line 255 of file instruction.c.
References instruction::op_second.
Referenced by s_evaluate().
instruction_load_program()
instruction_set_st* instruction_load_program (const char * file_path)
load an ASM program into the runtime.
Parameters
file_path path of asm file.
Returns
instruct_set loaded instruction sequence.
Definition at line 72 of file instruction.c.
References instruction_set::count, DEFAULT_ARRAY_SIZE, instruction_set::flag_register, instruction_set::instructs, label_table::label_table, label_table::label_table_capacity, label_table::label_table_size, instruction_set::labels, instruction_set::program_counter, s_load_program(), and s_replace_label().
Referenced by main().
instruction_set_get_flag()
int instruction_set_get_flag (instruction_set_st * instructions)
get the comparision result
Parameters
instruction_set a valid instruction_set object.
Returns
flag value.
Definition at line 181 of file instruction.c.
References instruction_set::flag_register.
Referenced by eval_bool_op_helper().
instruction_set_get_instruction()
instruction_st* instruction_set_get_instruction (instruction_set_st * instructions)
get next instruction from instruction set
Parameters
instruction_set a valid instruction_set object.
Returns
NULL, failed or no more instructions; otherwise a pointer to the instruction.
Definition at line 146 of file instruction.c.
References instruction_set::count, instruction_set::instructs, and instruction_set::program_counter.
Referenced by s_evaluate().
instruction_set_get_label()
unsigned int instruction_set_get_label (instruction_set_st * instructions, char * label)
look up a label address.
Parameters
instruction_st a valid instruction_set object.
label,the label string going to lookup.
Returns
a valid address for program counter, if label doesn't exist, exit.
Definition at line 205 of file instruction.c.
References label_info::address, label_info::label_name, label_table::label_table, label_table::label_table_size, and instruction_set::labels.
Referenced by eval_bool_op_helper().
instruction_set_set_flag()
void instruction_set_set_flag (instruction_set_st * instructions, int new_flag)
set a new comparision result
Parameters
instruction_set a valid instruction_set object.
new_flag new flag value.
Definition at line 192 of file instruction.c.
References instruction_set::flag_register.
Referenced by eval_cmp().
instruction_set_set_pc()
void instruction_set_set_pc (instruction_set_st * instructions, int new_pc)
set a new program counter
Parameters
instruction_set a valid instruction_set object.
new_pc new program counter address.
Definition at line 169 of file instruction.c.
References instruction_set::program_counter.
Referenced by eval_bool_op_helper().