SER502-Spring-2017-Team10: src/compiler/utils/symbol_table.h File Reference
symbol_table.h File Reference
Purpose: symbol table data structure.
Typedefs
typedef struct symbol_table symbol_table_st
Enumerations
enum type {
NONE = -1, KEYWORD = 0, IDENTIFIER = 1, BIN_OP = 2,
NUMBER = 3, DELIMITER = 4, BOOLEAN_OP = 5, ID = 6,
OPEN_PARENTHESES = 7, CLOSE_PARENTHESES = 8, OPEN_CURLY_BRACKETS = 9, CLOSE_CURLY_BRACKETS = 10
}
Functions
symbol_table_st * symbol_table_init ()
initialize the symbol table.
void symbol_table_fini (symbol_table_st *)
clean up the symbol table.
int symbol_table_lookup (symbol_table_st *, char *symbol)
look up the symbol on symbol table
int symbol_table_insert (symbol_table_st *, char *symbol, int token_type)
insert the symbol to symbol table
Detailed Description
Purpose: symbol table data structure.
Version
1.0
Date
04.15.2017
Author
Xiangyu Guo
Definition in file symbol_table.h.
Typedef Documentation
symbol_table_st
typedef struct symbol_table symbol_table_st
Definition at line 11 of file symbol_table.h.
Enumeration Type Documentation
type
enum type
Enumerator
NONE
KEYWORD
IDENTIFIER
BIN_OP
NUMBER
DELIMITER
BOOLEAN_OP
ID
OPEN_PARENTHESES
CLOSE_PARENTHESES
OPEN_CURLY_BRACKETS
CLOSE_CURLY_BRACKETS
Definition at line 14 of file symbol_table.h.
Function Documentation
symbol_table_fini()
void symbol_table_fini (symbol_table_st * symbol_table)
clean up the symbol table.
Parameters
symbol_table a valid symbol table object.
Definition at line 102 of file symbol_table.c.
References symbol::symbol, symbol_table::symbol_array, and symbol_table::table_size.
Referenced by lexical_analysis(), main(), and symbol_table_insert().
symbol_table_init()
symbol_table_st* symbol_table_init ()
initialize the symbol table.
Returns
a valid symbol table object.
Definition at line 38 of file symbol_table.c.
References symbol_table::array_size, BIN_OP, BOOLEAN_OP, CLOSE_CURLY_BRACKETS, CLOSE_PARENTHESES, DEFAULT_ARRAY_SIZE, DELIMITER, error_errno(), KEYWORD, OPEN_CURLY_BRACKETS, OPEN_PARENTHESES, symbol_table::symbol_array, symbol_table_insert(), and symbol_table::table_size.
Referenced by generate_stmt_list(), lexical_analysis(), main(), and symbol_table_insert().
symbol_table_insert()
int symbol_table_insert (symbol_table_st * symbol_table, char * symbol, int token_type)
insert the symbol to symbol table
Parameters
table a valid symbol table object.
symbol a symbol going to insert.
token_type the type of the token.
Returns
-1, failed; otherwise the index inserted in symbol table.
Parameters
table a valid symbol table object.
symbol a symbol going to insert.
token_val the value of the token.
Returns
-1, failed; otherwise the index inserted in symbol table.
Definition at line 151 of file symbol_table.c.
References symbol_table::array_size, ENLARGE_FACTOR, KEYWORD, main(), symbol::symbol, symbol_table::symbol_array, symbol_table_fini(), symbol_table_init(), symbol_table_insert(), symbol_table_lookup(), symbol_table::table_size, and symbol::token_type.
Referenced by generate_stmt_list(), lexical_analysis(), symbol_table_init(), and symbol_table_insert().
symbol_table_lookup()
int symbol_table_lookup (symbol_table_st * symbol_table, char * symbol)
look up the symbol on symbol table
Parameters
table a valid symbol table object.
symbol a symbol going to look up.
Returns
-1, not found; otherwise the index in symbol table.
Definition at line 122 of file symbol_table.c.
References symbol::symbol, symbol_table::symbol_array, symbol_table::table_size, and symbol::token_type.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_stmt(), generate_stmt_list(), lexical_analysis(), and symbol_table_insert().