SER502-Spring-2017-Team10: src/compiler/utils/symbol_table.c File Reference
symbol_table.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <stdbool.h>
#include "error.h"
#include "symbol_table.h"
Classes
struct symbol
struct symbol_table
Macros
#define DEFAULT_ARRAY_SIZE (16)
#define ENLARGE_FACTOR (2)
Typedefs
typedef struct symbol symbol_st
Functions
symbol_table_st * symbol_table_init ()
initialize the symbol table.
void symbol_table_fini (symbol_table_st *symbol_table)
clean up the symbol table.
int symbol_table_lookup (symbol_table_st *symbol_table, char *symbol)
look up the symbol on symbol table
int symbol_table_insert (symbol_table_st *symbol_table, char *symbol, int token_type)
insert the symbol to symbol table
Macro Definition Documentation
DEFAULT_ARRAY_SIZE
#define DEFAULT_ARRAY_SIZE (16)
Definition at line 18 of file symbol_table.c.
Referenced by symbol_table_init().
ENLARGE_FACTOR
#define ENLARGE_FACTOR (2)
Definition at line 19 of file symbol_table.c.
Referenced by symbol_table_insert().
Typedef Documentation
symbol_st
typedef struct symbol symbol_st
Function Documentation
symbol_table_fini()
void symbol_table_fini (symbol_table_st * symbol_table)
clean up the symbol table.
Parameters
symbol_table a valid symbol table object.
Definition at line 102 of file symbol_table.c.
References symbol::symbol, symbol_table::symbol_array, and symbol_table::table_size.
Referenced by lexical_analysis(), main(), and symbol_table_insert().
symbol_table_init()
symbol_table_st* symbol_table_init ()
initialize the symbol table.
Returns
a valid symbol table object.
Definition at line 38 of file symbol_table.c.
References symbol_table::array_size, BIN_OP, BOOLEAN_OP, CLOSE_CURLY_BRACKETS, CLOSE_PARENTHESES, DEFAULT_ARRAY_SIZE, DELIMITER, error_errno(), KEYWORD, OPEN_CURLY_BRACKETS, OPEN_PARENTHESES, symbol_table::symbol_array, symbol_table_insert(), and symbol_table::table_size.
Referenced by generate_stmt_list(), lexical_analysis(), main(), and symbol_table_insert().
symbol_table_insert()
int symbol_table_insert (symbol_table_st * symbol_table, char * symbol, int token_type)
insert the symbol to symbol table
Parameters
table a valid symbol table object.
symbol a symbol going to insert.
token_val the value of the token.
Returns
-1, failed; otherwise the index inserted in symbol table.
Definition at line 151 of file symbol_table.c.
References symbol_table::array_size, ENLARGE_FACTOR, KEYWORD, main(), symbol::symbol, symbol_table::symbol_array, symbol_table_fini(), symbol_table_init(), symbol_table_insert(), symbol_table_lookup(), symbol_table::table_size, and symbol::token_type.
Referenced by generate_stmt_list(), lexical_analysis(), symbol_table_init(), and symbol_table_insert().
symbol_table_lookup()
int symbol_table_lookup (symbol_table_st * symbol_table, char * symbol)
look up the symbol on symbol table
Parameters
table a valid symbol table object.
symbol a symbol going to look up.
Returns
-1, not found; otherwise the index in symbol table.
Definition at line 122 of file symbol_table.c.
References symbol::symbol, symbol_table::symbol_array, symbol_table::table_size, and symbol::token_type.
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_stmt(), generate_stmt_list(), lexical_analysis(), and symbol_table_insert().