SER502-Spring-2017-Team10: src/compiler/utils/link_list.h File Reference
link_list.h File Reference
Purpose: link_list data structure.
#include "link_node.h"
Macros
#define LINK_LIST_CONTINUE (1)
keep traverse
#define LINK_LIST_STOP (0)
stop traverse
Typedefs
typedef struct link_list link_list_st
typedef int(* cb_func) (link_node_st *, void *)
call back function
Functions
link_list_st * link_list_init ()
initialize the link list.
void link_list_free (link_list_st *list)
free the link list.
link_node_st * link_list_pop (link_list_st *)
pop out one element from the head of the list.
link_node_st * link_list_top (link_list_st *)
get the top one element from the head of the list.
link_node_st * link_list_append (link_list_st *, link_node_st *)
append one element to the end of the list.
int link_list_traverse (link_list_st *, cb_func callback, void *cb_data)
iterate on the link list and perform the callback on each element
Detailed Description
Purpose: link_list data structure.
Version
1.0
Date
04.15.2017
Author
Xiangyu Guo
Definition in file link_list.h.
Macro Definition Documentation
LINK_LIST_CONTINUE
#define LINK_LIST_CONTINUE (1)
keep traverse
Definition at line 13 of file link_list.h.
Referenced by generate_stmt_list(), handle_if_stmt_helper(), lexical_analysis(), link_list_traverse(), and print_byte_code().
LINK_LIST_STOP
#define LINK_LIST_STOP (0)
stop traverse
Definition at line 14 of file link_list.h.
Referenced by handle_if_stmt_helper(), link_list_traverse(), and print_byte_code().
Typedef Documentation
cb_func
typedef int(* cb_func) (link_node_st *, void *)
call back function
Definition at line 19 of file link_list.h.
link_list_st
typedef struct link_list link_list_st
Definition at line 16 of file link_list.h.
Function Documentation
link_list_append()
link_node_st* link_list_append (link_list_st * list, link_node_st * node)
append one element to the end of the list.
Parameters
list,a valid list head.
node,a valid list node.
Returns
NULL on failed, otherwise a cursor point to the tail of the list.
Definition at line 85 of file link_list.c.
References link_node_append(), and link_list::tail.
Referenced by byte_code_new(), emit_token(), generate_stmt_list(), and link_list_traverse().
link_list_free()
void link_list_free (link_list_st * list)
free the link list.
Parameters
list,a valid list going to release.
Definition at line 39 of file link_list.c.
References link_list::head, link_node_remove_all(), and link_list::tail.
Referenced by handle_if_stmt_helper(), lexical_analysis(), link_list_traverse(), and main().
link_list_init()
link_list_st* link_list_init ()
initialize the link list.
Returns
link_list a initialized link list.
Definition at line 26 of file link_list.c.
References error_errno(), link_list::head, link_node_new(), and link_list::tail.
Referenced by generate_stmt_list(), lexical_analysis(), link_list_traverse(), and semantic_analysis().
link_list_pop()
link_node_st* link_list_pop (link_list_st * list)
pop out one element from the head of the list.
Parameters
list,a valid list head.
Returns
NULL on failed, otherwise a valid link node.
Definition at line 52 of file link_list.c.
References link_list::head, link_node_append(), and link_node_get_next().
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_boolean_value(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt_list(), and link_list_traverse().
link_list_top()
link_node_st* link_list_top (link_list_st * list)
get the top one element from the head of the list.
Parameters
list,a valid list head.
Returns
NULL on failed, otherwise a valid link node.
Definition at line 69 of file link_list.c.
References link_list::head, and link_node_get_next().
Referenced by generate_boolean_expre(), generate_for_stmt(), generate_if_stmt(), generate_res1(), generate_res2(), generate_stmt(), and generate_stmt_list().
link_list_traverse()
int link_list_traverse (link_list_st * list, cb_func callback, void * cb_data)
iterate on the link list and perform the callback on each element
Parameters
list,a valid list head.
call_back,call back function going to perform, can be NULL.
Returns
1 on success, 0 on stoped.
Definition at line 100 of file link_list.c.
References link_list::head, link_list_append(), LINK_LIST_CONTINUE, link_list_free(), link_list_init(), link_list_pop(), LINK_LIST_STOP, link_list_traverse(), link_node_free(), link_node_get_data(), link_node_get_next(), link_node_new(), and main().
Referenced by generate_stmt_list(), handle_if_stmt_helper(), lexical_analysis(), link_list_traverse(), and main().