SER502-Spring-2017-Team10: src/runtime/instruction.c File Reference
instruction.c File Reference
Purpose: implemetation of the machine instruction.
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "instruction.h"
Classes
struct label_info
struct label_table
struct instruction
struct instruction_set
Macros
#define BUFFER_SIZE (255)
input buffer size
#define DEFAULT_ARRAY_SIZE (64)
dynamic array default size
#define RESIZE_FACTOR (2)
resize factor when dynamic array is too small
Typedefs
typedef struct label_info label_st
typedef struct label_table label_table_st
Functions
static int s_load_program (const char *, instruction_set_st *)
load an ASM program into the runtime.
static void s_replace_label (instruction_set_st *, label_table_st *)
replace label in ASM program into real address.
static void s_insert_label (label_table_st *, char *, unsigned int)
insert a label into label table.
instruction_set_st * instruction_load_program (const char *file_path)
load an ASM program into the runtime.
void instruction_clean_up (instruction_set_st *instructions)
clean up the instruction set.
instruction_st * instruction_set_get_instruction (instruction_set_st *instructions)
get next instruction from instruction set
void instruction_set_set_pc (instruction_set_st *instructions, int new_pc)
set a new program counter
int instruction_set_get_flag (instruction_set_st *instructions)
get the comparision result
void instruction_set_set_flag (instruction_set_st *instructions, int new_flag)
set a new comparision result
unsigned int instruction_set_get_label (instruction_set_st *instructions, char *label)
look up a label address.
char * instruction_get_op_code (instruction_st *instruction)
get operation code from an instruction.
char * instruction_get_op_first (instruction_st *instruction)
get operation code from an instruction.
char * instruction_get_op_second (instruction_st *instruction)
get operation code from an instruction.
Detailed Description
Purpose: implemetation of the machine instruction.
Version
1.0
Date
04.23.2017
Author
Xiangyu Guo
Definition in file instruction.c.
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE (255)
input buffer size
Definition at line 15 of file instruction.c.
Referenced by s_load_program().
DEFAULT_ARRAY_SIZE
#define DEFAULT_ARRAY_SIZE (64)
dynamic array default size
Definition at line 16 of file instruction.c.
Referenced by instruction_load_program().
RESIZE_FACTOR
#define RESIZE_FACTOR (2)
resize factor when dynamic array is too small
Definition at line 17 of file instruction.c.
Referenced by s_insert_label(), and s_load_program().
Typedef Documentation
label_st
typedef struct label_info label_st
label_table_st
typedef struct label_table label_table_st
Function Documentation
instruction_clean_up()
void instruction_clean_up (instruction_set_st * instructions)
clean up the instruction set.
Parameters
instructions,a valid instruction set object.
Definition at line 117 of file instruction.c.
References instruction_set::count, instruction_set::instructs, label_info::label_name, label_table::label_table, label_table::label_table_size, instruction_set::labels, instruction::op_code, instruction::op_first, and instruction::op_second.
Referenced by main().
instruction_get_op_code()
char* instruction_get_op_code (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
op_code, operation code
Definition at line 232 of file instruction.c.
References instruction::op_code.
Referenced by s_evaluate().
instruction_get_op_first()
char* instruction_get_op_first (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
operand, first operand
Definition at line 243 of file instruction.c.
References instruction::op_first.
Referenced by s_evaluate().
instruction_get_op_second()
char* instruction_get_op_second (instruction_st * instruction)
get operation code from an instruction.
Parameters
instruction,a valid instruction object.
Returns
operand, second operand
Definition at line 255 of file instruction.c.
References instruction::op_second.
Referenced by s_evaluate().
instruction_load_program()
instruction_set_st* instruction_load_program (const char * file_path)
load an ASM program into the runtime.
Parameters
file_path path of asm file.
Returns
instruct_set loaded instruction sequence.
Definition at line 72 of file instruction.c.
References instruction_set::count, DEFAULT_ARRAY_SIZE, instruction_set::flag_register, instruction_set::instructs, label_table::label_table, label_table::label_table_capacity, label_table::label_table_size, instruction_set::labels, instruction_set::program_counter, s_load_program(), and s_replace_label().
Referenced by main().
instruction_set_get_flag()
int instruction_set_get_flag (instruction_set_st * instructions)
get the comparision result
Parameters
instruction_set a valid instruction_set object.
Returns
flag value.
Definition at line 181 of file instruction.c.
References instruction_set::flag_register.
Referenced by eval_bool_op_helper().
instruction_set_get_instruction()
instruction_st* instruction_set_get_instruction (instruction_set_st * instructions)
get next instruction from instruction set
Parameters
instruction_set a valid instruction_set object.
Returns
NULL, failed or no more instructions; otherwise a pointer to the instruction.
Definition at line 146 of file instruction.c.
References instruction_set::count, instruction_set::instructs, and instruction_set::program_counter.
Referenced by s_evaluate().
instruction_set_get_label()
unsigned int instruction_set_get_label (instruction_set_st * instructions, char * label)
look up a label address.
Parameters
instruction_st a valid instruction_set object.
label,the label string going to lookup.
Returns
a valid address for program counter, if label doesn't exist, exit.
Definition at line 205 of file instruction.c.
References label_info::address, label_info::label_name, label_table::label_table, label_table::label_table_size, and instruction_set::labels.
Referenced by eval_bool_op_helper().
instruction_set_set_flag()
void instruction_set_set_flag (instruction_set_st * instructions, int new_flag)
set a new comparision result
Parameters
instruction_set a valid instruction_set object.
new_flag new flag value.
Definition at line 192 of file instruction.c.
References instruction_set::flag_register.
Referenced by eval_cmp().
instruction_set_set_pc()
void instruction_set_set_pc (instruction_set_st * instructions, int new_pc)
set a new program counter
Parameters
instruction_set a valid instruction_set object.
new_pc new program counter address.
Definition at line 169 of file instruction.c.
References instruction_set::program_counter.
Referenced by eval_bool_op_helper().
s_insert_label()
static void s_insert_label (label_table_st * labels, char * label, unsigned int addr) static
insert a label into label table.
Parameters
label_table a valid label table.
label the label string.
addr the address of the label.
label_table a valid label table.
label_str the label string.
addr the address of the label.
Definition at line 368 of file instruction.c.
References label_info::address, label_info::label_name, label_table::label_table, label_table::label_table_capacity, label_table::label_table_size, and RESIZE_FACTOR.
Referenced by s_load_program().
s_load_program()
static int s_load_program (const char * file_path, instruction_set_st * instructions) static
load an ASM program into the runtime.
Parameters
file_path ASM file path.
instruct_set [out] loaded instruction sequence.
Returns
total count of instructions.
Definition at line 267 of file instruction.c.
References BUFFER_SIZE, instruction_set::count, instruction_set::instructs, instruction_set::labels, instruction::op_code, instruction::op_first, instruction::op_second, RESIZE_FACTOR, and s_insert_label().
Referenced by instruction_load_program().
s_replace_label()
static void s_replace_label (instruction_set_st * instructions, label_table_st * labels) static
replace label in ASM program into real address.
Parameters
instruct_set [in/out] instructions going to replace.
labels [in] label table with real address.
Definition at line 340 of file instruction.c.
References label_info::address, instruction_set::count, instruction_set::instructs, label_info::label_name, label_table::label_table, label_table::label_table_size, and instruction::op_code.
Referenced by instruction_load_program().