SER502-Spring-2017-Team10: src/compiler/parser.c File Reference
parser.c File Reference
Purpose: implementation of parser.h which generate a parsing tree using token list and symbol table.
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include "utils/parsing_tree.h"
#include "utils/symbol_table.h"
#include "utils/link_list.h"
Functions
static void raise_syntax_error (int line_no, char *msg)
static parsing_tree_st * generate_decl_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the declare statement accordig to the grammar rule
static parsing_tree_st * generate_print_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the print statement accordig to the grammar rule
static parsing_tree_st * generate_assign_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the assignment statement accordig to the grammar rule
static parsing_tree_st * generate_if_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the if statement accordig to the grammar rule
static parsing_tree_st * generate_for_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the for statement accordig to the grammar rule
static parsing_tree_st * generate_expre (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the expression accordig to the grammar rule
static parsing_tree_st * generate_term (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the term accordig to the grammar rule
static parsing_tree_st * generate_factor (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the factor accordig to the grammar rule
static parsing_tree_st * generate_res1 (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the res1 accordig to the grammar rule
static parsing_tree_st * generate_res2 (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the res2 accordig to the grammar rule
static parsing_tree_st * generate_stmt (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the statement list recursively accordig to the grammar rule
static parsing_tree_st * generate_boolean_expre (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the boolean expression accordig to the grammar rule
static parsing_tree_st * generate_boolean_value (link_list_st *token_list, symbol_table_st *symbol_table)
: generate the boolean value accordig to the grammar rule
static parsing_tree_st * generate_stmt_list (link_list_st *, symbol_table_st *)
parsing_tree_st * syntax_analysis (link_list_st *token_list, symbol_table_st *symbol_table)
: get the token_list and symbol_table parse it into a parsing tree
Detailed Description
Purpose: implementation of parser.h which generate a parsing tree using token list and symbol table.
Version
1.0
Date
04.18.2017
Author
Ximing
Definition in file parser.c.
Function Documentation
generate_assign_stmt()
static parsing_tree_st * generate_assign_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the assignment statement accordig to the grammar rule
Parameters
Definition at line 530 of file parser.c.
References generate_expre(), IDENTIFIER, link_list_pop(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_sibling(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_stmt(), and raise_syntax_error().
generate_boolean_expre()
static parsing_tree_st * generate_boolean_expre (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the boolean expression accordig to the grammar rule
Parameters
Definition at line 261 of file parser.c.
References BOOLEAN_OP, generate_boolean_value(), generate_expre(), link_list_pop(), link_list_top(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_child(), parsing_tree_set_sibling(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_if_stmt(), and raise_syntax_error().
generate_boolean_value()
static parsing_tree_st * generate_boolean_value (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the boolean value accordig to the grammar rule
Parameters
Definition at line 301 of file parser.c.
References link_list_pop(), link_node_free(), link_node_get_data(), parsing_tree_new(), and parsing_tree_set_child().
Referenced by generate_boolean_expre(), and raise_syntax_error().
generate_decl_stmt()
static parsing_tree_st * generate_decl_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the declare statement accordig to the grammar rule
Parameters
Definition at line 362 of file parser.c.
References IDENTIFIER, link_list_pop(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_sibling(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_stmt(), and raise_syntax_error().
generate_expre()
static parsing_tree_st * generate_expre (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the expression accordig to the grammar rule
Parameters
Definition at line 496 of file parser.c.
References generate_res1(), generate_term(), parsing_tree_new(), parsing_tree_set_child(), and parsing_tree_set_sibling().
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_factor(), generate_for_stmt(), generate_print_stmt(), and raise_syntax_error().
generate_factor()
static parsing_tree_st * generate_factor (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the factor accordig to the grammar rule
Parameters
Definition at line 390 of file parser.c.
References generate_expre(), IDENTIFIER, link_list_pop(), link_node_free(), link_node_get_data(), NUMBER, OPEN_PARENTHESES, parsing_tree_new(), parsing_tree_set_child(), parsing_tree_set_sibling(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_res2(), generate_term(), and raise_syntax_error().
generate_for_stmt()
static parsing_tree_st * generate_for_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the for statement accordig to the grammar rule
Parameters
Definition at line 164 of file parser.c.
References generate_expre(), generate_stmt_list(), IDENTIFIER, link_list_pop(), link_list_top(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_sibling(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_stmt(), and raise_syntax_error().
generate_if_stmt()
static parsing_tree_st * generate_if_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the if statement accordig to the grammar rule
Parameters
Definition at line 57 of file parser.c.
References generate_boolean_expre(), generate_stmt_list(), link_list_pop(), link_list_top(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_sibling(), and raise_syntax_error().
Referenced by generate_stmt(), and raise_syntax_error().
generate_print_stmt()
static parsing_tree_st * generate_print_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the print statement accordig to the grammar rule
Parameters
Definition at line 511 of file parser.c.
References generate_expre(), link_list_pop(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_sibling(), and raise_syntax_error().
Referenced by generate_stmt(), and raise_syntax_error().
generate_res1()
static parsing_tree_st * generate_res1 (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the res1 accordig to the grammar rule
Parameters
Definition at line 429 of file parser.c.
References generate_term(), link_list_pop(), link_list_top(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_child(), and parsing_tree_set_sibling().
Referenced by generate_expre(), and raise_syntax_error().
generate_res2()
static parsing_tree_st * generate_res2 (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the res2 accordig to the grammar rule
Parameters
Definition at line 454 of file parser.c.
References generate_factor(), link_list_pop(), link_list_top(), link_node_free(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_child(), and parsing_tree_set_sibling().
Referenced by generate_term(), and raise_syntax_error().
generate_stmt()
static parsing_tree_st * generate_stmt (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the statement list recursively accordig to the grammar rule
Parameters
Definition at line 320 of file parser.c.
References generate_assign_stmt(), generate_decl_stmt(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), IDENTIFIER, link_list_top(), link_node_get_data(), parsing_tree_new(), parsing_tree_set_child(), raise_syntax_error(), and symbol_table_lookup().
Referenced by generate_stmt_list(), and raise_syntax_error().
generate_stmt_list()
static parsing_tree_st * generate_stmt_list (link_list_st * token_list, symbol_table_st * symbol_table) static
Definition at line 570 of file parser.c.
References CLOSE_CURLY_BRACKETS, DELIMITER, generate_stmt(), IDENTIFIER, link_list_append(), LINK_LIST_CONTINUE, link_list_init(), link_list_pop(), link_list_top(), link_list_traverse(), link_node_free(), link_node_get_data(), link_node_new(), main(), parsing_tree_get_data(), parsing_tree_new(), parsing_tree_prefix_traverse(), parsing_tree_set_child(), parsing_tree_set_sibling(), raise_syntax_error(), symbol_table_init(), symbol_table_insert(), symbol_table_lookup(), syntax_analysis(), and TREE_TRAVERSE_CONTINUE.
Referenced by generate_for_stmt(), generate_if_stmt(), raise_syntax_error(), and syntax_analysis().
generate_term()
static parsing_tree_st * generate_term (link_list_st * token_list, symbol_table_st * symbol_table) static
: generate the term accordig to the grammar rule
Parameters
Definition at line 481 of file parser.c.
References generate_factor(), generate_res2(), parsing_tree_new(), parsing_tree_set_child(), and parsing_tree_set_sibling().
Referenced by generate_expre(), generate_res1(), and raise_syntax_error().
raise_syntax_error()
static void raise_syntax_error (int line_no, char * msg) static
Definition at line 18 of file parser.c.
References generate_assign_stmt(), generate_boolean_expre(), generate_boolean_value(), generate_decl_stmt(), generate_expre(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_res1(), generate_res2(), generate_stmt(), generate_stmt_list(), and generate_term().
Referenced by generate_assign_stmt(), generate_boolean_expre(), generate_decl_stmt(), generate_factor(), generate_for_stmt(), generate_if_stmt(), generate_print_stmt(), generate_stmt(), and generate_stmt_list().
syntax_analysis()
parsing_tree_st* syntax_analysis (link_list_st * token_list, symbol_table_st * symbol_table)
: get the token_list and symbol_table parse it into a parsing tree
Parameters
Definition at line 557 of file parser.c.
References generate_stmt_list(), parsing_tree_new(), and parsing_tree_set_child().
Referenced by generate_stmt_list(), and main().