SER502-Spring-2017-Team10: src/compiler/compiler.c File Reference
compiler.c File Reference
Purpose: main entrance of the compiler.
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "utils/link_list.h"
#include "utils/symbol_table.h"
#include "utils/parsing_tree.h"
#include "utils/error.h"
#include "lexical.h"
#include "parser.h"
#include "byte_code.h"
Functions
int print_byte_code (link_node_st *node, void *cb_data)
print out the data in the link list node.
static void s_usage ()
output the usage information about the compiler
int main (int argc, char *argv[])
main entrance of the compiler.
Detailed Description
Purpose: main entrance of the compiler.
Version
1.0
Date
04.16.2017
Author
Xiangyu Guo
Definition in file compiler.c.
Function Documentation
main()
int main (int argc, char * argv[])
main entrance of the compiler.
Parameters
argc arguments count.
argv arguments vector.
Returns
0 on success; otherwise errno.
Definition at line 51 of file compiler.c.
References error_errno(), lexical_analysis(), link_list_free(), link_list_traverse(), parsing_tree_free(), print_byte_code(), s_usage(), semantic_analysis(), symbol_table_fini(), symbol_table_init(), and syntax_analysis().
Referenced by generate_stmt_list(), handle_if_stmt_helper(), lexical_analysis(), link_list_traverse(), link_node_remove_all(), parsing_tree_prefix_traverse(), and symbol_table_insert().
print_byte_code()
int print_byte_code (link_node_st * node, void * cb_data)
print out the data in the link list node.
Parameters
node a valid link node.
Returns
LINK_LIST_CONTINUE, next node; LINK_LIST_STOP, stop here.
Definition at line 30 of file compiler.c.
References LINK_LIST_CONTINUE, LINK_LIST_STOP, link_node_get_data(), and s_usage().
Referenced by handle_if_stmt_helper(), and main().
s_usage()
static void s_usage () static
output the usage information about the compiler
Definition at line 98 of file compiler.c.
Referenced by main(), and print_byte_code().